### ISSUE TITLE
Issue with 8.3

### ISSUE THREAD

**Issue by zoecarver** [Rocla/lfs-7.8#7]
When I run chapter 8.3 I get an error saying :
<pre><code>
... Post-Installing
cp: cannot stat 'arch/x86/boot/bzImage': No such file or directory
cp: cannot stat 'System.map': No such file or directory
cp: cannot stat '.config': No such file or directory
... Configuring Linux Module Load Order
</code></pre>

I don't know why this is happening.
I am running kubuntu and installing lfs on a separate drive. Thanks for making such an awesome project! after I get this one working I would love to make a BLFS extension.

**Comment by RomainClaret** [comment]
Hello 😊
Sorry for the answer delay 😔

I am not sure also where the problem comes from, sadly it's not custom code I made 😔 It's from the book at page 237.

I found something on the net for this error. Could you check if this is any use for you?
[https://answers.launchpad.net/lfscript/+question/251085](https://answers.launchpad.net/lfscript/+question/251085)

p.s. I would really love a bfs extension :)

**Comment by zoecarver** [comment]
I finally figured it out (there was a problem compiling the kernel) Thanks! I think I am going to start a blfs extension. So I know what the best way to write it is, did you just copy and past everything from the book? or is there some kind of automation I could use? Thanks again for you help!

**Comment by RomainClaret** [comment]
Well, most is from the book of course :) But not only, but automation also requires to think about it a bit haha.
For example: https://github.com/Rocla/lfs-7.8/blob/master/2.3-root_create-files-system-on-partitions.sh#L58-L86
I am not sure what answer you are looking for :-/ The idea is that the script is following the steps from the book. Not just the code provided in the book.

**Comment by zoecarver** [comment]
Ok, Thanks! Here is the repo that I am working on. I know that there are a lot of things wrong with my code, but it is a work in progress :). I don't know if you want to add my repository to yours when its done, or if you just want yours to be LFS. either works for me :). Thanks again for making such and awesome project!
link to my code: https://github.com/funfood/BLFS

**Comment by RomainClaret** [comment]
Watching :) Thank you
